name: Deploy to Sandbox

on:
  push:
    branches:
      - "*"

jobs:
  Test:
    uses: ./.github/workflows/test.yaml

  Deploy-Sandbox:
    needs: Test
    uses: './.github/workflows/deploy.yaml'
    secrets: inherit
    with:
      environment: sandbox

